---
title: "Fishing from Sea, On a Sailboat"
date: 2019-08-26
---

title: Fishing from Sea, On a Sailboat
author: Keith
email: mhtyfman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
